import { readFile } from "node:fs/promises";

export interface BrowserCookie {
  name: string;
  value: string;
  domain: string;
  path: string;
  expires?: number;
  secure?: boolean;
  httpOnly?: boolean;
  sameSite?: string;
}

export interface CookieExport {
  version: 1;
  generatedAt: string;
  source: "pro-cli-cdp";
  targetUrl: string;
  origins: string[];
  cookies: BrowserCookie[];
}

const CHATGPT_ORIGINS = [
  "https://chatgpt.com/",
  "https://auth.openai.com/",
  "https://openai.com/",
  "https://sentinel.openai.com/",
  "https://ws.chatgpt.com/",
] as const;

export function chatGptOrigins(): string[] {
  return [...CHATGPT_ORIGINS];
}

export function toCookieExport(cookies: BrowserCookie[]): CookieExport {
  return {
    version: 1,
    generatedAt: new Date().toISOString(),
    source: "pro-cli-cdp",
    targetUrl: "https://chatgpt.com/",
    origins: chatGptOrigins(),
    cookies: sanitizeCookies(cookies),
  };
}

export function sanitizeCookies(cookies: BrowserCookie[]): BrowserCookie[] {
  const deduped = new Map<string, BrowserCookie>();
  for (const cookie of cookies) {
    if (!cookie.name || cookie.value === undefined) continue;
    const domain = stripLeadingDot(cookie.domain || "chatgpt.com");
    const path = cookie.path || "/";
    deduped.set(`${cookie.name}|${domain}|${path}`, {
      name: cookie.name,
      value: cookie.value,
      domain,
      path,
      ...(cookie.expires ? { expires: cookie.expires } : {}),
      ...(cookie.secure !== undefined ? { secure: cookie.secure } : {}),
      ...(cookie.httpOnly !== undefined ? { httpOnly: cookie.httpOnly } : {}),
      ...(cookie.sameSite ? { sameSite: cookie.sameSite } : {}),
    });
  }
  return [...deduped.values()].sort((left, right) => left.name.localeCompare(right.name));
}

export function cookieSummary(cookies: BrowserCookie[]): {
  count: number;
  domains: string[];
  names: string[];
  expired: number;
} {
  const now = Date.now() / 1000;
  const domains = new Set<string>();
  const names = new Set<string>();
  let expired = 0;
  for (const cookie of cookies) {
    domains.add(stripLeadingDot(cookie.domain));
    names.add(cookie.name);
    if (cookie.expires && cookie.expires <= now) expired += 1;
  }
  return {
    count: cookies.length,
    domains: [...domains].sort(),
    names: [...names].sort(),
    expired,
  };
}

export async function loadCookieExport(path: string): Promise<CookieExport> {
  const raw = await readFile(path, "utf8");
  const parsed = JSON.parse(raw) as CookieExport | BrowserCookie[] | { cookies: BrowserCookie[] };
  if (Array.isArray(parsed)) return toCookieExport(parsed);
  if ("cookies" in parsed && !("version" in parsed)) return toCookieExport(parsed.cookies);
  return parsed as CookieExport;
}

export function toCookieHeader(cookies: BrowserCookie[]): string {
  const now = Date.now() / 1000;
  return sanitizeCookies(cookies)
    .filter((cookie) => !cookie.expires || cookie.expires > now)
    .map((cookie) => `${cookie.name}=${cookie.value}`)
    .join("; ");
}

export function toNetscapeCookieJar(cookies: BrowserCookie[]): string {
  const lines = [
    "# Netscape HTTP Cookie File",
    "# Generated by pro-cli. Raw cookie values are sensitive.",
  ];
  for (const cookie of sanitizeCookies(cookies)) {
    const domain = stripLeadingDot(cookie.domain);
    const includeSubdomains = cookie.domain.startsWith(".") ? "TRUE" : "FALSE";
    const secure = cookie.secure ? "TRUE" : "FALSE";
    const expires = Math.trunc(cookie.expires ?? 0);
    lines.push(
      [domain, includeSubdomains, cookie.path || "/", secure, expires, cookie.name, cookie.value].join(
        "\t",
      ),
    );
  }
  return `${lines.join("\n")}\n`;
}

function stripLeadingDot(domain: string): string {
  return domain.startsWith(".") ? domain.slice(1) : domain;
}
